CREATE SCHEMA IF NOT EXISTS practice01;

CREATE TABLE IF NOT EXISTS practice01.departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_code text NOT NULL UNIQUE,
    dept_name text NOT NULL
);

CREATE TABLE IF NOT EXISTS practice01.students (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    email text NOT NULL UNIQUE,
    dept_id bigint NOT NULL REFERENCES practice01.departments(id)
);

CREATE TABLE IF NOT EXISTS practice01.courses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code text NOT NULL UNIQUE,
    title text NOT NULL,
    credits integer NOT NULL CHECK (credits > 0),
    dept_id bigint NOT NULL REFERENCES practice01.departments(id),
    seats_available integer NOT NULL CHECK (seats_available >= 0)
);

CREATE TABLE IF NOT EXISTS practice01.enrollments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL REFERENCES practice01.students(id) ON DELETE CASCADE,
    course_id bigint NOT NULL REFERENCES practice01.courses(id),
    status text NOT NULL DEFAULT 'enrolled'
        CHECK (status IN ('enrolled', 'completed', 'withdrawn')),
    grade integer CHECK (grade BETWEEN 0 AND 100),
    enrolled_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (student_id, course_id)
);

CREATE INDEX IF NOT EXISTS enrollments_course_idx ON practice01.enrollments (course_id);
