CREATE SCHEMA IF NOT EXISTS lab01;

CREATE TABLE IF NOT EXISTS lab01.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    email text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lab01.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku text NOT NULL UNIQUE,
    product_name text NOT NULL,
    unit_price numeric(10, 2) NOT NULL CHECK (unit_price >= 0),
    stock integer NOT NULL CHECK (stock >= 0)
);

CREATE TABLE IF NOT EXISTS lab01.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_ref text NOT NULL UNIQUE,
    customer_id bigint NOT NULL REFERENCES lab01.customers(id),
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'paid', 'shipped', 'cancelled')),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lab01.order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES lab01.orders(id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES lab01.products(id),
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(10, 2) NOT NULL CHECK (unit_price >= 0),
    UNIQUE (order_id, product_id)
);

CREATE INDEX IF NOT EXISTS orders_customer_created_idx
    ON lab01.orders (customer_id, created_at DESC);

CREATE INDEX IF NOT EXISTS order_items_product_idx
    ON lab01.order_items (product_id);
